version: '3'

services:
  # Django web service
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use the development Dockerfile (or Dockerfile.prod for production)
    container_name: ams
    image: ams-web:v.0.2
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Migrate DB and start the server
    volumes:
      - .:/app  # Bind mount the current directory to /app inside the container
    ports:
      - "8000:8000"  # Expose port 8000 for Django
    depends_on:
      - db  # Ensure the database service starts first
    env_file:
      - .env  # Load environment variables (optional)

  # PostgreSQL database service
  db:
    image: postgres:17.3  # Use the official PostgreSQL 13 image
    environment:
      POSTGRES_DB: postgres  # Define the database name (same as in Django settings)
      POSTGRES_USER: postgres  # Define the database user (same as in Django settings)
      POSTGRES_PASSWORD: root  # Define the password (same as in Django settings)
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist the database data
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL

volumes:
  db_data:  # Define volume to persist PostgreSQL data
