version: '3'

services:
  ams-web:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use the development Dockerfile (or Dockerfile.prod for production)
    container_name: ams-web
    image: ams-web:v.0.1
    depends_on:
      - db
    command: >
      sh -c "/usr/local/bin/wait-for-it db:5432 -- python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 ams.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh  # Mount the script correctly
      - ./static:/app/static  # Ensure static files are correctly placed here
    networks:
      - ams_network

  db:
    image: postgres:17.3
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Define the database name (same as in Django settings)
      POSTGRES_USER: ${POSTGRES_USER}  # Define the database user (same as in Django settings)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Define the password (same as in Django settings)
    volumes:
      - ams_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ams_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config file
    ports:
      - "80:80"
    depends_on:
      - ams-web
    networks:
      - ams_network

volumes:
  ams_db_data:
    driver: local

networks:
  ams_network:
    driver: bridge
