version: '3'

services:
  ams-web:
    #    image: vivekath1/ams-web:v.1.1   # Pull from Docker Hub
    #    Pull from Docker Hub< before pull push from local follow below steps>
    #    1. docker build --platform linux/amd64 -f Dockerfile.dev -t ams-web:v.0.1 . <OR> docker build -f Dockerfile.dev -t ams-web:v.0.1 .
    #    2. docker tag ams-web:v.0.1 vivekath1/ams-web:v.0.1
    #    3. docker push vivekath1/ams-web:v.0.1
    #
    image: ams-web:v.0.1   # take from Docker Desktop or can directly take from Docker Desktop
    container_name: ams-web
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"  # Exposing port 8000 for the web app
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh   # Mount the wait-for-it.sh script into the container
      - ./logs:/var/log/django
    networks:
      - ams_network

  db:
    image: postgres:17.3
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ams_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Exposing port 5432 on the host for PostgreSQL
    networks:
      - ams_network

volumes:
  ams_db_data:  # This will be created locally for PostgreSQL data
    driver: local

networks:
  ams_network:
    driver: bridge
