apiVersion: v1
kind: Service
metadata:
  name: service-my-nodedb-app
spec:
  selector:
    app: nodedb-app  # Select pods with the label 'app: nginx'
  ports:
    - protocol: TCP
      port: 8080  # Port that the service will expose
      targetPort: 3000  # Port on the container that the service will forward traffic to
  type: LoadBalancer  # Default type, makes the service accessible only inside the cluster
