apiVersion: v1
kind: Service
metadata:
  name: service-ams-web
spec:
  selector:
    app: ams-web  # Select pods with the label 'app: nginx'
  ports:
    - protocol: TCP
      port: 80  # Port that the service will expose
      targetPort: 8000  # Port on the container that the service will forward traffic to
  type: LoadBalancer  # Default type, makes the service accessible only inside the cluster
