# Generated by Django 4.2.16 on 2025-02-09 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=200)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(default='', max_length=200)),
                ('sortname', models.CharField(default='', max_length=200)),
                ('countrycode', models.CharField(default='', max_length=200)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Contries',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Usertype',
                'verbose_name_plural': 'Usertypes',
                'db_table': 'usertype',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='callingcode',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='createddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updateddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='users',
            table='auth_user',
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=200)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='custom_auth.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitecity', to='custom_auth.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitecountry', to='custom_auth.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitestate', to='custom_auth.state')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
                ('site_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteleave', to='custom_auth.site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeealeave', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningdate', models.DateTimeField(null=True)),
                ('min_wages', models.FloatField(default=0.0)),
                ('qualification', models.CharField(default='', max_length=250)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
                ('site_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteinformation', to='custom_auth.site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeinformation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='stateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='custom_auth.state'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half_day')], max_length=1, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('createddate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updateddate', models.DateTimeField(null=True)),
                ('site_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteattendance', to='custom_auth.site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeattendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='custom_auth.city'),
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='custom_auth.country'),
        ),
        migrations.AddField(
            model_name='users',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='custom_auth.state'),
        ),
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='custom_auth.usertype'),
        ),
    ]
