# Generated by Django 4.2.16 on 2025-02-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='owner',
            new_name='owner_user',
        ),
    ]
