# Generated by Django 4.2.16 on 2025-02-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_city_country_usertype_alter_users_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
    ]
