# Generated by Django 4.2.16 on 2025-02-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_rename_owner_site_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeeattendance', to='custom_auth.employee'),
        ),
    ]
