# Generated by Django 4.2.16 on 2025-03-06 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_attendance_updateddate_alter_city_updateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='city',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='country',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='site',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='updateddate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
