# Generated by Django 4.2.16 on 2025-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_remove_attendance_user_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
