# Generated by Django 4.2.16 on 2025-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_employee_is_on_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
