# Generated by Django 4.2.16 on 2025-02-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_attendance_date_alter_leave_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_password_set',
        ),
    ]
