# Generated by Django 4.2.16 on 2025-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_remove_users_is_password_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half_day'), ('OT', 'Over_time')], max_length=2, null=True),
        ),
    ]
